
server:
    port: 8086

##Druid config
druid:
    username: future
    password: future123
spring:
    application:
        name: pq-job-admin
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: test
        url: jdbc:mysql://47.92.82.130:3306/db_job?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
        password: zxapp@2709
        # druid
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    ## Freemarker 配置
    freemarker:
      template-loader-path: classpath:/templates
      cache: true
      charset: utf-8
      content-type: text/html
      suffix: .ftl
      expose-spring-macro-helpers: true
      expose-request-attributes: true
      expose-session-attributes: true
      request-context-attribute: request
      check-template-location: true
      settings:
          template_update_delay: 0
          default_encoding: UTF-8
          output_encoding: UTF-8
          locale: zh_CN
          number_format: 0.##########
          date_format: yyyy-MM-dd
          time_format: HH:mm:ss
          datetime_format: yyyy-MM-dd HH:mm:s
          classic_compatible: true
          template_exception_handler: ignore

mybatis:
    basepackage: com.xxl.job.admin.mapper
    xmlLocation: classpath:mapper/**/*.xml
quartz:
    configLocation: quartz.properties


#xxl-job配置
xxl:
    job:
        ### jedi-job email
        mail:
            host: smtp.exmail.qq.com
            port: 25
            username: zhitao0902@163.com
            password: yeqian999@sina
            sendNick: '《prod任务调度平台JEDI-JOB》'
        ### jedi-job login
        login:
            username: admin
            password: admin123456
        ### jedi-job, access token
        accessToken: ''
        ### jedi-job, i18n (default empty as chinese, "en" as english)
        i18n: ''
    #执行器基础定义
    jobInfo:
        jobGroup: 2  #执行器主键ID	XXL_JOB_QRTZ_TRIGGER_GROUP.id
        jobCronEveryDay: '0 0 2 * * ?' #每天凌晨2点执行
        jobCronManual: '0 0 2 * * ? 2099' #手动执行
        executorFailStrategy: FAIL_ALARM # 失败处理策略(FAIL_ALARM(失败警告)/FAIL_RETRY(失败重试))
        author: 'system' # 责任人
        alarmEmail: '' # 报警邮件 多个邮箱,分割
        executorRouteStrategy: ROUND  #路由策略
        glueType: BEAN  #运行模式 Bean模式
        executorHandler: sparkJobHandler #执行JobHandler方法
        executorBlockStrategy: SERIAL_EXECUTION #阻塞处理策略 单机串行

###################################
# 日志配置
###################################
logging:
    level:
        root: info
        xxl.job.admin: debug
    path: /Users/liutao/data/logs/pq-job-admin